apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t-proton-name-content-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "" # an empty string "" will use the default StorageClass
