secret_key_base: 7AeHwVeGGJuxvHsV14LYUTwP1626Be1_5DO7FfP9tWU
port: 3000
name: t.proton.name

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: sqlite3:./db/t.proton.name_development.db
auto_reload: true

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

pipes:
  static:
    headers:
      "Cache-Control": "no-store"

secrets:
  description: Store your development secrets credentials and settings here.
